### PR TITLE
fix: RSSfeed get added without backend connection

### LINKED ISSUE #197: RSS-Feed getting added on UI screen even without any connection to backend.
**Describe the bug**
If a user does not run the flood backend and tries to add an rss feed the feed gets added to the app rss-feed UI list which should not happen and an error should be returned.

**To Reproduce**

1. Go to homepage and click add rss-feed button on the top right.
2. Add a rss-feed without running the flood backend.
3. The rss-feed feed get displayed in the rss-feed list in the app's UI.

**Expected behavior**
If flood backend is not running then the rss-feed should not get added to the app's rss-feed UI showing existing added rss-feed and instead should remind the user to connect to the backend by displaying a message/toast etc.

### PR DESCRIPTION
**Pull request by amitamrutiya2210**
Fixes #197 

Describe the changes you have made in this PR -
Gist: Checking if the backend is connected when clicking on the save option if not show a snack bar with a msg.

Implementation:

- Created a `checkClientOnline` function that makes calls to the backend and checks whether the status code is 200 or not.
- The function is implemented in the save button of the RSS feed bottom sheet

Demo of the changes-

https://github.com/CCExtractor/Flood_Mobile/assets/91112485/4d4dee61-b75e-48f0-bd27-29a12291f958

### CODE REVIEW

**Comment by Akshatji800** [comment]
@amitamrutiya2210 check my comment in files changed tab

**Comment by amitamrutiya2210** [comment]
I am not able to see any comment on files changed tag.

**Comment by Akshatji800** [comment]
image
check this line. What do u mean by 43?

**Comment by Akshatji800** [comment]
@amitamrutiya2210 resolve the conflicts as well

**Comment by amitamrutiya2210** [comment]
> image check this line. What do u mean by 43?

I think I mistakenly did this. There is no such meaning to that. I have fixed this issue, so now you can proceed with the review.

**Pull request merged**
