### PR TITLE
Migration to Null-Safety code.

### PR DESCRIPTION
**Pull request by prajwal27**
The initial steps of migrating to null-safe are committed. The branch is yet to be tested.

### CODE REVIEW

**Comment by prajwal27** [comment]
@pratikbaid3  I have issues in setting up the backend. I went through the installation guide, I wasn't able to go past the WEB UI under preferences as per the guide.

**Comment by prajwal27** [comment]
image
I'm stuck at this point.

**Comment by pratikbaid3** [comment]
@prajwal27 please join the slack channel for CCExtractor so that we can discuss the changes and the issue that you are having. https://ccextractor.org/public/general/support/

**Comment by prajwal27** [comment]
image
The problem while logging into flood.

**Pull request merged**
