### PR TITLE
Feature/snack bar feature

### PR DESCRIPTION
**Pull request by arq0017**
Fixes #

Describe the changes you have made in this PR -
Added **snackbar** for :  
1. Adds torrent 
2. Remove torrent
3. Creating new user of setting page

Screenshots of the changes (If any) 
added_torrent
removed_torrent

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by arq0017** [comment]
Please review the pr . Thankyou !

**Comment by pratikbaid3** [comment]
Thank you @arq0017. I'll go through the PR and get back to you.

**Comment by arq0017** [comment]
> Thank you @arq0017. I'll go through the PR and get back to you.

Noted sir !

**Comment by pratikbaid3** [comment]
@arq0017 Please change the destination to the "develop" branch

**Comment by arq0017** [comment]
> @arq0017 Please change the destination to the "develop" branch
> https://github.com/CCExtractor/Flood_Mobile/blob/master/CONTRIBUTING.md

@pratikbaid3 updated base branch to develop branch!

**Comment by pratikbaid3** [comment]
@arq0017 Please create seperate PR for each feature/issue. This pr currently contains both the logout popup and the snackbar

**Comment by arq0017** [comment]
@pratikbaid3 I am new to git. So I am stuck on how to create new PR. I have already committed the changes.

**Comment by pratikbaid3** [comment]
Hi. You can revert your previous commit and then create a new branch from the develop branch in your local repository. So what will happen is that you will have a logout branch with logout popup and a snackbar branch with snackbar related changes. And then you can create 2 seperate PR's.

**Comment by arq0017** [comment]
The merge conflict is resolved.

**Comment by pratikbaid3** [comment]
@arq0017 This PR also contains changes for the logout popup. Please create a separate PR that only has changes related to the snack bar.

**Pull request closed without merging**
