### PR TITLE
Fixed light theme colour issue for bottom sheet

### PR DESCRIPTION
**Pull request by ManavSarkar**
Fixed the Theme changing error to the light version

The error was due to wrong theme usage which lead to unusual UI.

### CODE REVIEW

**Comment by Akshatji800** [comment]
@ManavSarkar the issue still continues in the add torrent through torrent file option bottom sheet. Please fix it there also.

**Comment by ManavSarkar** [comment]
Please check it again

**Comment by Akshatji800** [comment]
@ManavSarkar please squash the commits into a single commit.

**Comment by ManavSarkar** [comment]
I have squashed them into one

**Comment by ManavSarkar** [comment]
@Akshatji800 kindly check the conflict, maybe any other person has changed the theme type meanwhile

**Comment by ManavSarkar** [comment]
Here is the required output
https://user-images.githubusercontent.com/42129636/218300819-901f60e9-0903-4fa9-b742-bf06acd842fe.mp4

**Comment by ManavSarkar** [comment]
@Akshatji800 here is new attached output

https://user-images.githubusercontent.com/42129636/219589747-e6e4c863-de79-4573-aecb-5f9f0394f7db.mp4

**Pull request merged**
