### PR TITLE
Add circular theme change animation

### LINKED ISSUE #117: Improving the theme-changing feature and adding an animation to it to make the theme switching look better.
**Is your feature request related to a problem? Please describe.**
Currently the animation looks a bit weird while changing the theme from dark mode to light mode and vice versa.

**Describe the solution you'd like**
The theme-changing feature can be improved by adding an animation to it to make the theme switching look better.

**Additional context**
Sample implementation:
1_gZTqvTmrf4rq9rMYtyMI8g

### PR DESCRIPTION
**Pull request by letsintegreat**
Fixes #117 

Describe the changes you have made in this PR -

As described in this [blog](https://maheshmnj.medium.com/leveraging-clippaths-in-flutter-a5f34c795ae5), I have implemented a theme changing animation. The basic principle is that the app will have two instances of HomeScreen stacked on top of each other at all times. One of them will be dark themed, and another light themed. As soon as the user toggles theme, the other instance will be shown with animation.

Screenshots of the changes -

https://user-images.githubusercontent.com/37345795/209331138-3700ea72-77b1-43f1-bb14-015e514b8f30.mp4

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Akshatji800** [comment]
@letsintegreat thanks for the PR. The changes look great just there are some concerns regarding the CI failing due to formatting issues (refer attached screenshot). Please resolve them. Also, there are errors introduced in the unit and widget tests written for the app because of the changes you made. Resolve these errors also and then we can proceed further with the PR merging process. 

image

**Comment by letsintegreat** [comment]
@Akshatji800 Thanks for reviewing, I have addressed both the problems.

**Comment by Akshatji800** [comment]
@letsintegreat there is an issue noticed by me. The add torrent button on clicking shows a white blur background which was blackish in the earlier version of the app before this PR. Please resolve this issue.

<table>
<tr>
<td align="center"> <br /><b>Previous State</b></a><br /></td>
<td align="center"><br /><b>After PR Changes State</b></a><br /></td>
</tr>
</table>

**Comment by Akshatji800** [comment]
@letsintegreat is there any update/progress? We are planning to have a new release soon and expect this feature to be a part of the new release. Please let me know if you are facing any issues while working on the feature - I am happy to help.

**Pull request closed without merging**
