### PR TITLE
Issue-48:fix-Simple UI Bug in logout alert dialog

### LINKED ISSUE #48: Simple UI bug in logout alert dialog
**Bug Description**
There is a simple UI bug in logout alert dialog. The 'Yes' and 'No' buttons are not displayed as it should.

**To Reproduce**

1. Go to 'options by sliding the main dashboard towards right'
2. Click on 'Logout'
3. See error in 'Yes' and 'No' button alignment.

**Expected behavior**
The 'Yes' and 'No' button should be aligned side by side.

**Screenshots**
<table>
<tr>
<td align="center"> <br /><b>Present State</b></a><br /></td>
<td align="center"><br /><b>How it should look</b></a><br /></td>
</tr>
</table>

**Device Information**

- OS: [Android-11]
- Device Name: realme 7 pro

**Are you working on this issue? (Yes)**

### PR DESCRIPTION
**Pull request by Akshatji800**
Fixes #48 

**Changes you have made in this PR -**
- Minimal changes to solve the 'Yes' & 'No' Button UI bug in logout alert dialog.

**Screenshots of the changes -**
<table>
<tr>
<td align="center"> <br /><b>Bug State</b></a><br /></td>
<td align="center"><br /><b>How it will look after changes made in PR</b></a><br /></td>
</tr>
</table>

### CODE REVIEW

**Comment by Akshatji800** [comment]
@pratikbaid3  Sir I solved the issue because of which the build was failing. Now it can be merged.

**Comment by pratikbaid3** [comment]
@Akshatji800 I am unable to recreate this issue. Please specify the device you tested it on.

**Comment by Akshatji800** [comment]
@pratikbaid3 Sir the device on which I tested it is realme 7 pro.
I am attaching a screen recording of the issue here:

https://user-images.githubusercontent.com/73401649/148336620-e507246a-610f-4a0c-b90c-d3521da89c79.mp4

**Comment by pratikbaid3** [comment]
Closing this PR since the issue cannot be replicated.

**Pull request closed without merging**
