### PR TITLE
issue 132 display size of traker in filter torrent menu

### LINKED ISSUE #132: Display the size beside each tracker listed under filter by trackers.
**Is your feature request related to a problem? Please describe.**
The size can be displayed beside each tracker listed under filter by trackers in the same way as in the flood web app.

**Describe the solution you'd like**
Display the size beside each tracker listed under filter by trackers.

**Additional context**
Screenshot_38

### PR DESCRIPTION
**Pull request by amitamrutiya2210**
###  Adding a size tracker similar to Flood Web
Fixes #132 

- First adds a `sizeList` in tracker
- Then in event handler, updates the `sizeList`
- Finally displays the size along with the names
- Also displays the sizes in required format(MB, GB, KB etc)

Screenshots of the changes (If any) -
Screenshot 2023-05-12 201524 (New size 1)

In PR #188, there is an unresolved issue related to RangeError (index) that has persisted for a long time. Therefore, I have created a new PR to fix this issue.

### CODE REVIEW

**Comment by Akshatji800** [comment]
@amitamrutiya2210 the size is not getting displayed in filter by tags. Please check the web version how it is done. Also can you try to change the size displaying text colour to blueGrey or something else and see if it looks better.

**Comment by amitamrutiya2210** [comment]
Okay i will implement it.

**Comment by amitamrutiya2210** [comment]
@Akshatji800 you can review my PR I changed it according to your suggestion. It's look like this.

image (Custom)

**Comment by Akshatji800** [comment]
@amitamrutiya2210  check why the CI is failing there is something called SText is used which is making the issues. Suspect it to be a typo.

**Comment by amitamrutiya2210** [comment]
Okay I fix those issue and squash it. Additionally, I removed old `flutter_client_sse` package folder in this PR that is not relevant to our project.

**Comment by Akshatji800** [comment]
@amitamrutiya2210 for me the PR still shows these as the current version after building it locally
image

**Pull request merged**
