### PR TITLE
Added new screenshots and updated them to the README file

### LINKED ISSUE #173: Update readme.md with new pictures of the app screens
**Is your feature request related to a problem? Please describe.**
- Currently readme.md contains the old version app photos.

**Describe the solution you'd like**
- Update those with new pictures

### PR DESCRIPTION
**Pull request by virajbhartiya**
Fixes #173 

I've updated the screenshots of the app and added them to the README.md file

### CODE REVIEW

**Comment by Akshatji800** [comment]
@virajbhartiya resolve the conflicts and this is okay but according to me the one I put as example with camera notch was looking better than the current one. See if you can change that as well

**Comment by Akshatji800** [comment]
> @virajbhartiya resolve the conflicts and this is okay but according to me the one I put as example with camera notch was looking better than the current one. See if you can change that as well

Also squash the commits

**Comment by virajbhartiya** [comment]
Is it okay if I delete this pull request and create a new PR with a single commit?

**Comment by Akshatji800** [comment]
No you can easily squash the commits

**Comment by virajbhartiya** [comment]
I'm trying to squash them but after resolving the conflicts it's just adding more commits to the PR. Can you please help me with this?

**Comment by Akshatji800** [comment]
> I'm trying to squash them but after resolving the conflicts it's just adding more commits to the PR. Can you please help me with this?

@virajbhartiya these things are easy to figure out just google how to squash a commit using git cli

**Comment by virajbhartiya** [comment]
Hey @Akshatji800, I've squashed the commits.

**Pull request closed without merging**
