### PR TITLE
notify user when press back button for exit

### PR DESCRIPTION
**Pull request by amitamrutiya2210**
issue #162 

If the user accidentally presses the back button, the app will close. To fix this, the user must press the back button twice continuously to exit the app. A toast message will also appear if the user only taps the back button once.

Screenshot_1673783166 (Custom)

### CODE REVIEW

**Comment by Akshatji800** [comment]
@amitamrutiya2210 you can't make a PR directly for a feature/bug in any open-source contribution. The same goes here also. Please create a issue first using report a bug/request a feature template and then a PR can be raised for the issue on approval.

**Comment by amitamrutiya2210** [comment]
As I am new to open source contributer and was unaware. I will make sure this mistake does not occur in the future.

**Comment by Akshatji800** [comment]
> As I am new to open source contributer and was unaware. I will make sure this mistake does not occur in the future.

Yeah @amitamrutiya2210 this is understandable. I was just making you aware with the contribution guidelines to avoid mistakes from your side in future. Thanks for understanding :)

**Comment by Akshatji800** [comment]
@amitamrutiya2210 looks good but the toast message is even getting displayed when the app gets exit. Please resolve this and this.

**Comment by Akshatji800** [comment]
@amitamrutiya2210 is there any progress with this?

**Comment by amitamrutiya2210** [comment]
I forgot to resolve this issue. Now i work on this.

**Pull request merged**
