### PR TITLE
add filter by tag feature

### LINKED ISSUE #29: Tags
Feature:
Ability to add, search and filter based on tags.

- [ ] Option for the user to add a new tag
- [ ] Option to choose from existing tags
- [ ] Filter the torrent list based on a tag
- [ ] Untag a torrent

### PR DESCRIPTION
**Pull request by amitamrutiya2210**
Fixes #29 

User can able to filter by existing tags
Screenshot_1673633098 (Custom)

### CODE REVIEW

**Comment by Akshatji800** [comment]
@amitamrutiya2210 this is great progress but there are certain more things to be done before this PR could be merged as mentioned in the [issue-29](https://github.com/CCExtractor/Flood_Mobile/issues/29).
- Option for the user to add a new tag
- Option to choose from existing tags
-  Untag a torrent
More Info: On long pressing a particular torrent you might see a dialog box poping up showing three different options with one option as set tags. This feature should work also along with the filter feature you currently implemented.

**Comment by amitamrutiya2210** [comment]
Okay i will add this feature soon.

**Comment by Akshatji800** [comment]
> @amitamrutiya2210 this is great progress but there are certain more things to be done before this PR could be merged as mentioned in the [issue-29](https://github.com/CCExtractor/Flood_Mobile/issues/29).
> 
> * Option for the user to add a new tag
> * Option to choose from existing tags
> * Untag a torrent
>   More Info: On long pressing a particular torrent you might see a dialog box poping up showing three different options with one option as set tags. This feature should work also along with the filter feature you currently implemented.

@amitamrutiya2210 still features such as untag a torrent is not implemented. Please look into it to get this PR merged.

**Comment by amitamrutiya2210** [comment]
I looked at flood web UI but I could not find any way to untag a torrent. Currently, flood API only has a PATCH API for tagging torrents. I cannot untag torrents using this API. Can you suggest how to implement this untag feature?

**Comment by Akshatji800** [comment]
@amitamrutiya2210  please resolve the conflicts to get this PR merged.

**Review by Akshatji800 — APPROVED** [review]

**Pull request merged**
