### PR TITLE
Solved Theme bug, issue: #149

### PR DESCRIPTION
**Pull request by AntoTomAbraham**
issue #149 solved
Changes Made :

### CODE REVIEW

**Comment by amitamrutiya2210** [comment]
@AntoTomAbraham , you can wrap the container with an `InputDecorator` widget, which will give the container a default outline border. Also The `InputDecorator` widget changes the color of the border according to the theme of the app. For reference you can refer this [https://github.com/CCExtractor/Flood_Mobile/pull/136/files](url).

**Comment by AntoTomAbraham** [comment]
> @AntoTomAbraham ,I think you can wrap the container with an `InputDecorator` widget, which will give the container a default outline border. Also The `InputDecorator` widget changes the color of the border according to the theme of the app. For reference you can refer this [https://github.com/CCExtractor/Flood_Mobile/pull/136/files](url).

Thank your @amitamrutiya2210

**Comment by Akshatji800** [comment]
@AntoTomAbraham still the bug continues for the divider between each feed/rule i.e is not visible in the light mode of the app.

Screenshots showing the bug:
<table>
<tr>
<td align="center"> <br /><b>Light-Mode(RSS-Feed)</b></a><br /></td>
<td align="center"><br /><b>Light-Mode(Download Rules)</b></a><br /></td>
</tr>
</table>

**Comment by AntoTomAbraham** [comment]
>

**Comment by Akshatji800** [comment]
@AntoTomAbraham please squash the commits into a single commit.

**Pull request closed without merging**
