### PR TITLE
fix: home_screen_widget_test.dart failing

### LINKED ISSUE #150: home_screen_widget_test.dart page widget tests failing.
**Describe the bug**
The home_screen_widget_test.dart page widget tests have started failing after the new features added to the screen.

**To Reproduce**

1. Go to android-studio and navigate to test folder.
2. Search for home_screen_widget_test.dart file and run the widget test by clicking on the green run button beside the main function.
3. Widget test written in the home_screen_widget_test.dart file will start running.
4. See errors.

**Expected behavior**
The widget tests failing should be changed and should be written according to the new features implemented so that they should pass.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Sudhanva-Nadiger**
Fixes #150

Describe the changes you have made in this PR - The home screen test file failed as new features were added. 
Those were solved and written new test cases according to the current home screen

- Screenshots of the changes (If any) 

image
#
image

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Akshatji800** [comment]
@Sudhanva-Nadiger please resolve the conflicts to get this PR merged.

**Comment by Sudhanva-Nadiger** [comment]
Yess I will do that !

**Comment by Sudhanva-Nadiger** [comment]
hi @Akshatji800 I have resolved the conflicts in my local system and push those commits ! I have two concerns 
1. The package "package/http/http.dart" was giving the error, so I updated its version and the error was gone
2. In rssHomePage.dart there is unused import, should I remove it ? 
Thanks.

**Comment by Sudhanva-Nadiger** [comment]
@Akshatji800 did not expect this from this repository! I had worked on these so hard and you just close the pr by merging some other guys pr ! this is not fair ! you should not have assigned to me if you wanted to merge the other guys pr !

**Comment by Akshatji800** [comment]
> @Akshatji800 did not expect this from this repository! I had worked on these so hard and you just close the pr by merging some other guys pr ! this is not fair ! you should not have assigned to me if you wanted to merge the other guys pr !

Hello @Sudhanva-Nadiger I understand your concern but I will explain you why I was compelled to do that:
- After you wrote the test a lot of changes were made to the home_screen so obviously the widget test also got changed a lot. So even though you gave time to this PR I was not able to merge it as it became sort of obsolete for the new changes. If I would have been known that you are still around I would have asked you only to make the changes.

**Pull request closed without merging**
