### PR TITLE
implement new upload and download speed graph feature

### LINKED ISSUE #45: Graph that represents the upload and the download speed.
The **Flood Web UI** has a graph on the left side of the screen that depicts the upload and the download speed. I want to implement a similar graph(rather a chart) for the same purpose keeping in consideration the Web UI and the Mobile UI theme.

### PR DESCRIPTION
**Pull request by amitamrutiya2210**
Fixes #45 

I try to implement graph that increases and decrease based on upload and download speed . This graph is similar that available in flood website.

https://user-images.githubusercontent.com/91112485/211987592-3d2e4956-efb3-4b7b-8b7c-94a7ae2eb704.mp4

### CODE REVIEW

**Comment by Akshatji800** [comment]
@amitamrutiya2210 this looks very good. Just few things need to be addressed and we are good to go.
- The size of the searchbar changes weirdly after the user enables the graph option. Please fix this.
- The toggle button given to change the visibility of the graph can be changed to some other button type which shows what it represents actually and on enabling it what expected will happen. Maybe try a graph icon button/flutter chip type button etc.

**Comment by amitamrutiya2210** [comment]
@Akshatji800 I am trying to change the height of the PullToReveal widget dynamically when the graph is turned on or off, but I am facing some issues. Can you help me solve this problem?

**Comment by Akshatji800** [comment]
> @Akshatji800 I am trying to change the height of the PullToReveal widget dynamically when the graph is turned on or off, but I am facing some issues. Can you help me solve this problem?

@amitamrutiya2210 see if this helps you :)
https://stackoverflow.com/questions/57471139/flutter-change-dialog-height-after-show

**Comment by amitamrutiya2210** [comment]
I done lots of changes in my new commit so I close this PR and make new PR with new changes.

**Pull request closed without merging**
