### PR TITLE
Add user accounts displaying section

### LINKED ISSUE #129: Add user accounts displaying section under authentication in the settings.
**Is your feature request related to a problem? Please describe.**
User accounts displaying section can be added under authentication in the settings in the same way as it is currently in the flood web app.

**Describe the solution you'd like**
User accounts displaying section under authentication in the settings can be added.

**Additional context**
imageedit_0_5712601901

### PR DESCRIPTION
**Pull request by letsintegreat**
Closes #129 

Tasks achieved in this PR -

1. **Display the list of users**: Wrote a function `getUsersList` in `AuthApi` to find the list of users (Refer the attached picture).
2. **Add username to SharedPreferences**: Because I could not find any way to find the current user via API, I added the current username to `SharedPreferences` along with token, which gets destroyed after the user has logged out.
3. **Delete a user**: If the current user is an admin, they will be able to delete any of the other users with a single tap. Wrote a function `deleteUser` in `AuthApi` which handles the API.
4. **Restrict non admin users from updating Authentication settings**: I check on Flood web app, if the user is not an admin, they are not able to change any of the settings under Authentication head, but this was not the case in the mobile app. So, I have handled the case when user is not an admin (Refer the attached picture).
5. **Update tests for UserDetailsProvider**: Because now `username` is also getting stored in `SharedPreferences` along with `token`, thus made the necessary changes in `user_detail_provider_unit_test.dart` to cover that portion too.

Screenshots of the changes -

**User Accounts List -**

**Not Admin -**

**Ref of web app, when user is not admin -**

### CODE REVIEW

**Comment by Akshatji800** [comment]
@letsintegreat if there is only one user present then eventhough if the user does not have the admin privileges then also he/she should be able to access the authentication options. Please have a look into this.

**Comment by Akshatji800** [comment]
@letsintegreat is there any update/progress? We are planning to have a new release soon and expect this feature to be a part of the new release. As I can see this feature is almost implemented and just requires few more patches from your side. Please let me know if you are facing any issues while working on the feature - I am happy to help. Also, please let me know if you want any other developer to collaborate with you on the issue - I am happy to assign one.

**Comment by amitamrutiya2210** [comment]
> @letsintegreat if there is only one user present then eventhough if the user does not have the admin privileges then also he/she should be able to access the authentication options. Please have a look into this.

@Akshatji800 I don’t know when this type of situation occurs, because the first user created is by default an admin and non-admin users cannot access authentication features. So they cannot remove the admin user. Therefore in every situation, there is at least one admin. Can you suggest when this type of situation occurs, where there is only one user and the user is not an admin?

**Comment by Akshatji800** [comment]
Closing this PR as multiple API calling was causing issues.

**Pull request closed without merging**
